Support dark mode
hbb20/CountryCodePickerProject pull request #503
Opened 2021-08-27 23:09 UTC by alishari

I have implemented dark mode support using material colors #450

2022-01-21 13:15 UTC, hbb20 requested changes
Thank you for the PR. I am sure this will be helpful to many devs. Although, we should correct the colors of demo app itself. Like following:
<img width="361" alt="image" src="https://user-images.githubusercontent.com/4918760/150533199-75666cdc-1403-4729-93fc-bed6d3a27452.png">

2022-08-03 17:43 UTC, darcishED commented on app/src/main/res/layout/fragment_full_number.xml
> +                    android:background="?attr/colorSurface"
[minor] could be shortened to ?/colroSurface .. it doesn't need to be explicitly defined

2022-08-03 17:46 UTC, darcishED commented on app/src/main/res/layout/fragment_full_number.xml
> +                    android:background="?attr/colorSurface"
[minor] could be shortened to ?/colroSurface .. it doesn't need to be explicitly defined

2022-08-03 17:46 UTC, darcishED commented on app/src/main/res/layout/fragment_full_number.xml
> +                    android:background="?attr/colorSurface"
same here

2022-08-03 17:46 UTC, darcishED commented on app/src/main/res/layout/fragment_introduction.xml
> +                    android:background="?attr/colorSurface"
same here

2022-08-03 17:46 UTC, darcishED commented on app/src/main/res/layout/fragment_introduction.xml
> +                    android:background="?attr/colorSurface"
same here

2022-08-03 17:50 UTC, darcishED reviewed
[EOF} Add an empty line at the end of all files

2022-08-03 17:50 UTC, darcishED commented on app/build.gradle
> +    implementation 'com.google.android.material:material:1.4.0'
update version

2022-08-03 17:50 UTC, darcishED commented on ccp/src/main/res/layout/layout_recycler_country_tile.xml
>          android:paddingLeft="10dp"
Why keep this if there is paddindStart?

2023-01-16 01:07 UTC, closed without merging